# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_auto_20170515_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='group',
        ),
    ]
